#! /bin/sh

# Mouse speed
xinput --set-prop "Logitech Gaming Mouse G402" "libinput Accel Speed" -0.9 &

# Transparency
picom -f &

# Fix the pointer for BSPWM
xsetroot -cursor_name left_ptr &

# Load background
source ~/.fehbg &

# Load polybar
./.config/polybar/launch.sh --cuts

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1.5
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config focused_border_color "#80a8fd"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
